### PR TITLE
Fix AP_end_indices

### PR DESCRIPTION
**Pull request by AurelienJaquier**
AP_end_indices does not give expected results for dendritic spikes, because they are not sharp enough.
This PR solves this issue by not looking for AP_end_indices between two spikes, but between the point where the negative derivative is the strongest and the next spike.

### CODE REVIEW

**Review by anilbey — APPROVED** [review]
Great

**Comment by wvangeit** [comment]
@AurelienJaquier it looks like the major version number is not updated?

**Comment by AurelienJaquier** [comment]
I just pushed it

**Comment by wvangeit** [comment]
I just realized i mentioned minor version number. But that's ok, i guess eFEL was overdue for a major version number increase :-)
Best to push the tag into the branch before the merge.

**Comment by AurelienJaquier** [comment]
oh, sorry. I'll push the tag before next time

**Pull request merged**
