### PR TITLE
small fix in documentation

### PR DESCRIPTION
**Pull request by AurelienJaquier**
## Description

python efeature was not linked for a particular feature in the documentation

## Checklist:
- [skip ] Unit tests are added to cover the changes (skip if not applicable).
- [skip ] The changes are mentioned in the documentation (skip if not applicable).
- [ skip] CHANGELOG file is updated (skip if not applicable).

### CODE REVIEW

**Comment by darshanmandge** [comment]
Could you also update the examples documentation [page](https://efel.readthedocs.io/en/latest/examples.html) with the new examples in [repository](https://github.com/BlueBrain/eFEL/tree/master/examples) ?

**Comment by AurelienJaquier** [comment]
> Could you also update the examples documentation [page](https://efel.readthedocs.io/en/latest/examples.html) with the new examples in [repository](https://github.com/BlueBrain/eFEL/tree/master/examples) ?

done in latest commits

**Comment by AurelienJaquier** [comment]
For the wheels tests, `macos-latest` has recently been updated to version `14`, and our workflow can't find any python when using this version, so I reverted to what used to be `macos-latest` before the update: `macos-12`.

**Review by anilbey — APPROVED** [review]
Wow great, thanks

**Pull request merged**
