### PR TITLE
Fix time constant in Lib1

### PR DESCRIPTION
**Pull request by AurelienJaquier**
Should fix time constant for Issue #211.

I found two problems in the time constant algorithm.
1./ The start index was increased by 10 for no apparent reason (Does anyone knows why this was there?). This made the example taken form Issue #211 miss the beginning of the decay.

2./ The error estimator used in the time constant algorithm (average RSS) does not allow comparison between datasets ranging over different scales. But the scale of 'log_v' is very dependent on the 'newx' value. I decided to use the normalized standard deviation as the error estimator (which allows us to compare data at different scales).

The example from Issue #211 gives consistent time constants when using this PR.

### CODE REVIEW

**Comment by wvangeit** [comment]
I assume this stim_start increase was there to avoid stimulus artifacts at the beginning of the stimulus. 
I think we're gonna have to look at this PR more closely, because as far as i can see it might significantly affect the values returned by efel for these features.

**Comment by AurelienJaquier** [comment]
I agree that it have a significant effect on the returned value. Here is a little plot comparing the values returned both with and without this PR in the case cm=1.0 of the example from Issue #211.
plot_1 0

**Comment by AurelienJaquier** [comment]
I investigated a little bit further the different ways of computing the error.

simple rss:
When we do a simple rss, like in efel, we see that the error is minimal at x near 0, but there is a maximum at x=0.1. Since the algorithm initialize in the slope at the right of the maximum, it will follow the slope towards larger x, and never find the 'true' minimum. Like I explained before, this tendency for the rss error to go down for larger x in this case is due to the logarithm to have smaller values at large x (in this particular example), thus the rss error on these values will also tend to be small.
rss

normalized rss:
The solution I implemented compensate for this change of scale by normalizing, and is able to find the right minimum. But it also has a problem: when the mean is near 0, the division creates an asymptote and this is prone to errors.
norm_mean_rss

rss normalized by range:
One solution can be to normalize the rss, not by the mean of the values we want to fit, but by the range they expand on. This both compensate the change of scale, and avoid asymptotes, since the range is not susceptible to go to almost 0.
norm_range_rss

**Comment by wvangeit** [comment]
Ok, so the normalization by range would make sense. Could we still combine this with skipping the 10 points in the beginning though, so that we would skip a possible transient.

**Comment by AurelienJaquier** [comment]
Ok, I put back the 10 points skipping.

**Comment by wvangeit** [comment]
@AurelienJaquier could you also tag the last commit as '3.2' (and don't forget to push it to the remote). That way this will get a new minor version number so that we can track when this change happened.

**Comment by AurelienJaquier** [comment]
Ok, I tagged the last commit as 3.2

**Pull request merged**
