### PR TITLE
An eFEL setting to specify the tolerated precision difference

### PR DESCRIPTION
**Pull request by anilbey**
As demonstrated in #174, certain operations such as LinearInterpolation may result in a small precision loss. In features such as the voltage_base calculation, that small precision loss is changing the size of the vector to compute the voltage base on. I.e. voltage_base was getting computed with one less element in the voltage vector. 

* This PR introduces a setting to control the amount of precision loss to tolerate. 
* It applies the setting on voltage_base, not to lose the last element in the computation.
* Since many other features depend on voltage_base, the expected_results.json is updated.
* Script to update the expected_results.json is also updated to encode numpy.integer values as python int values.

The last commit is tagged as eFEL version 3.1

### CODE REVIEW

**Comment by wvangeit** [comment]
@anilbey would you mind making a plot that shows which features have changed in the expectedresults.json and by how much, you can ignore the features that don't change. It's difficult in the git diff to see the feature changes. (maybe you can add that script to the repo, it might be useful in the future, doesn't have to be a complicated script)

**Comment by anilbey** [comment]
Ok, let me do that. Shall I take the mean for the features that have a list of values?

**Comment by wvangeit** [comment]
Yep, mean is ok.

**Comment by anilbey** [comment]
Here's the plot.
Plot

**Comment by wvangeit** [comment]
I was actually not expecting such a relatively large difference. It's not necessarily a blocker, but is the difference in voltage_base in this case caused by just 1 data point difference in the voltage trace?

**Comment by anilbey** [comment]
It is because Expected results is computed on testdata.txt 
https://github.com/BlueBrain/eFEL/blob/master/efel/tests/testdata/allfeatures/testdata.txt
The unit test for voltage_base is computed on mean_frequency_1.txt
https://github.com/BlueBrain/eFEL/blob/master/efel/tests/testdata/basic/mean_frequency_1.txt

For mean_frequency_1.txt it is caused by just one data point. For testdata.txt I expect the same but I haven't checked yet.

**Comment by anilbey** [comment]
The difference is not that much on testdata.txt either.
Here are the values on testdata.txt (on master branch):
C++
sum = -37762.719108
count = 500
mean = -75.52543822
Python
sum = -37838.15292306073
count = 501
mean = -75.52525533545052

difference = 0.00018288066615923526

**Comment by anilbey** [comment]
Yes I noticed that. I don't understand the reason. 
When I use testdata.txt instead of mean_frequency_1.txt in test_voltagebase1(), I get the 0.000182 difference.
Something must be different in test_all_features function.

**Comment by anilbey** [comment]
Yes the difference is that large when `stim_start` is 700 on `testdata.txt`.

* Python params:
sum: -52374.85609125951
count: 701
mean: -74.71448800464981

* C++ params:
sum: -52298.985042
count: 700
mean: -74.71283577400435

* diff: -0.0016522306454618274

**Comment by anilbey** [comment]
In fact before this PR,  `test_voltagebase1` would fail had the `stim_start` been set to 700 instead of 500.

**Comment by wvangeit** [comment]
Ok, so I guess I'll merge ?

**Comment by anilbey** [comment]
I think it is okay.

**Comment by wvangeit** [comment]
Ok, did you tag the version ? (and did you push the tag ?)

**Comment by anilbey** [comment]
I pushed the tag now.

**Pull request merged**
