### PR TITLE
Added GitHub Action to run tox.

### PR DESCRIPTION
**Pull request by AurelienJaquier**

### CODE REVIEW

**Comment by wvangeit** [comment]
Could it be that it has to be main.yml?

**Comment by AurelienJaquier** [comment]
@wvangeit I think that the yaml file can be named whatever we want, but if you prefer, I can rename it main.yml

**Comment by wvangeit** [comment]
I'm asking, because it seems the actions are not automatically triggered at the moment?

**Comment by wvangeit** [comment]
(they're also not appearing in the 'Actions' tab of the github page)

**Comment by AurelienJaquier** [comment]
Oh, ok. I think it's because we have to merge the change first, and once it is merged, each pull request will trigger the actions.

**Comment by wvangeit** [comment]
Let's see

**Comment by wvangeit** [comment]
Ok.it looks like the Actions are enabled now. However, the tests don't seem to be running for python 3.x:
https://github.com/BlueBrain/eFEL/runs/1511059680?check_suite_focus=true

**Comment by AurelienJaquier** [comment]
My best guess is that we should test for py27 and py3 (and not py35, py36, etc.). The difference between envlist and envdir in tox.ini confused me. I'll make the change and hopefully it will work.

**Comment by wvangeit** [comment]
We should keep testing for separate python versions though

**Comment by AurelienJaquier** [comment]
Alright. Then I'll keep what I changed, and change tox's envlist and envdir. If it's ok with you, I'll test for py 35, 36, 37 and 38.

**Pull request merged**
