### PR TITLE
Do some doc cleanup

### PR DESCRIPTION
**Pull request by mgeplf**
* Remove un-needed pdf files
* Remove trailing whitespace
* mv figures to _static directory

### CODE REVIEW

**Comment by mgeplf** [comment]
are the .pdf files needed in figures?
I was in the process of adding the dependency graph and couldn't help myself.

**Comment by wvangeit** [comment]
Pdf files ?

**Comment by mgeplf** [comment]
docs/source/figures/inv_ISI.pdf for example

**Comment by wvangeit** [comment]
I think we need them. Guess that Christian added these so that we can edit the figures later.

**Comment by mgeplf** [comment]
ah, in that case, I'd better add them back in...

**Comment by wvangeit** [comment]
oh, I didn't see you deleted these in that pull request. Yes, indeed, please put them back.

**Comment by mgeplf** [comment]
Do you think the original source files are around? Those would be better, probably

**Comment by wvangeit** [comment]
Would just put the pdfs back, that's more than enough.

**Pull request merged**
