### PR TITLE
Update pyfeatures.py

### PR DESCRIPTION
**Pull request by anirban6908**
Added the depolarization block check to the pyfeatures. It is customized to use for bluepyopt optimization.

### CODE REVIEW

**Comment by anirban6908** [comment]
Hey @wvangeit ..I actually started doing what you suggested i.e., updated the expected results but  it turned out the check depolarization code is raising false alarm for the example voltage trace you already have in repo. It is classifying it as a depolarization block. I will work on the code, I just didn't have time. The problem is that depolarization block threshold (at -50mv)  is sort of set arbitrarily. I do have traces, where the model actually suffers from depolarization block, and this code identifies it correctly but I need to fix the code so that it doesn't raise false alarm. Do you have anything like spiking threshold in your efel feature list? Specifying the depolarization threshold to the spiking threshold might be an easy fix to this problem.

**Comment by wvangeit** [comment]
@anirban6908, ok. Which trace raises a false alarm ?
Regarding your question about the spike threshold. Do you mean the spike 'detection' threshold, or the voltage at which the AP starts ?

**Comment by anirban6908** [comment]
@wvangeit The one in [testdata.txt](https://github.com/BlueBrain/eFEL/blob/master/efel/tests/testdata/allfeatures/testdata.txt).
Also by threshold I mean the voltage at which the AP starts. Detection threshold is the one you set manually right? (default at -20mV)

**Comment by wvangeit** [comment]
For voltage at AP start, you can use the feature AP_begin_voltage.
Yes, the detection threshold can be set manually.

**Pull request closed without merging**
