### PR TITLE
Update Neo integration for NWB support

### PR DESCRIPTION
**Pull request by ilkilic**
This PR updates NEO integration to support NWB formats and introduces a new example that demonstrate how to load data with NEO.

## Checklist:
- [x] Unit tests are added to cover the changes (skip if not applicable).
- [x] The changes are mentioned in the documentation (skip if not applicable).
- [ ] CHANGELOG file is updated (skip if not applicable).

### CODE REVIEW

**Review by anilbey — COMMENTED** [review]
Thanks, looks great.

Could you address the following also:
- the name of the example can be more explicit perhaps `nwb-via-neo` or `load-nwb` or something similar
- If possible, in the notebook besides the interspike interval, could you show at least one other feature? The sonata-network notebook is also showing the interspike interval feature. Some different feature/features would be good to show on the experimental data. E.g. perhaps some burst related feature as Rajnish mentioned. cc @darshanmandge which features may be suited for this experimental NWB
- Could you modify the docs/examples_to_rst.sh script @AurelienJaquier had created to make sure this notebook will be rendered in the docs?

**Comment by darshanmandge** [comment]
Thanks @ilkilic ! You can use this burst related features: [spikes_per_burst](https://efel.readthedocs.io/en/latest/eFeatures.html#python-efeature-spikes-per-burst), [strict_burst_number](https://efel.readthedocs.io/en/latest/eFeatures.html#python-efeature-strict-burst-number), [strict_burst_mean_freq](https://efel.readthedocs.io/en/latest/eFeatures.html#libv5-strict-burst-mean-freq)

**Comment by ilkilic** [comment]
I have made the requested changes in the latest commits

**Comment by anilbey** [comment]
Wow looks so good, thanks a lot @ilkilic

**Review by anilbey — APPROVED** [review]

**Pull request merged**
