### PR TITLE
Add documentation for some features

### PR DESCRIPTION
**Pull request by AurelienJaquier**
Add docs for irregularity index as asked in #226

Also add docs for some other features which docs were missing.

### CODE REVIEW

**Comment by DrTaDa** [comment]
Thanks !

**Comment by wvangeit** [comment]
Thx, @AurelienJaquier. I saw that during the merge of your previous PR the deployment step failed. Can you have a look if this happens again for this merge.

**Comment by AurelienJaquier** [comment]
@wvangeit The fail of the deployment is due to an update in `cibuildwheel`, the package that we use to build the wheels. It now, by default, also build wheels for musllinux (which it didn't before). 
It looks like it's complicated to make this musllinux wheel work, as even very general package we need to test the wheel, as `scipy`, does not have a musllinux wheel. 
I propose we solve this by simply skipping the musllinux wheels building, and keep building only the same wheels as before.

**Comment by wvangeit** [comment]
yeah, makes sense

**Pull request merged**
