### PR TITLE
Added parsing and output of dependency graph

### PR DESCRIPTION
**Pull request by mgeplf**
* parses Dependency.txt style files
* Outputs graphviz, or flat text
* as suggested by feature:
    https://github.com/BlueBrain/eFEL/issues/6

### CODE REVIEW

**Comment by wvangeit** [comment]
Can you add a target to the Makefile to build this ? 
Maybe we commit an example so that it can be visualised on github ?

**Comment by mgeplf** [comment]
Ok.

The diagram is huge, fyi.

**Comment by wvangeit** [comment]
You mean huge in file size ? Can it be rasterized ?

**Comment by mgeplf** [comment]
I added a target for the Makefile.

I don't think we should upload the graph yet.  It probably needs a bit more love by someone who is more talented with graphviz, and can have it layout better.

**Comment by wvangeit** [comment]
Ok, understood, thanks for the Makefile target

**Comment by wvangeit** [comment]
Cool graph ... :-)

**Pull request merged**
